"""perf: add indexes to frequently queried columns

Revision ID: 0b1d50a7fe43
Revises: d5fa4a71a08d
Create Date: 2026-07-09 11:47:13.911779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b1d50a7fe43'
down_revision = 'd5fa4a71a08d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_job_recommendation_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_job_recommendation_run_student_profile_id'), ['student_profile_id'], unique=False)

    with op.batch_alter_table('ai_skill_match_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_skill_match_run_internship_id'), ['internship_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_skill_match_run_student_profile_id'), ['student_profile_id'], unique=False)

    with op.batch_alter_table('internship', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_internship_lifecycle_status_id'), ['lifecycle_status_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_internship_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_internship_moderation_status_id'), ['moderation_status_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_internship_technology_category_id'), ['technology_category_id'], unique=False)

    with op.batch_alter_table('internship_application', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_internship_application_internship_id'), ['internship_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_internship_application_student_profile_id'), ['student_profile_id'], unique=False)

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_recipient_user_id'), ['recipient_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_recipient_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_is_read'))

    with op.batch_alter_table('internship_application', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_internship_application_student_profile_id'))
        batch_op.drop_index(batch_op.f('ix_internship_application_internship_id'))

    with op.batch_alter_table('internship', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_internship_technology_category_id'))
        batch_op.drop_index(batch_op.f('ix_internship_moderation_status_id'))
        batch_op.drop_index(batch_op.f('ix_internship_location_id'))
        batch_op.drop_index(batch_op.f('ix_internship_lifecycle_status_id'))

    with op.batch_alter_table('ai_skill_match_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_skill_match_run_student_profile_id'))
        batch_op.drop_index(batch_op.f('ix_ai_skill_match_run_internship_id'))

    with op.batch_alter_table('ai_job_recommendation_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_job_recommendation_run_student_profile_id'))

    # ### end Alembic commands ###
