"""Add company_size, industry_category, founding_year to CompanyProfile

Revision ID: 1976d3e4d596
Revises: 4834eb6d6355
Create Date: 2026-07-11 13:37:32.118499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1976d3e4d596'
down_revision = '4834eb6d6355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('industry_category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('company_size', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('founding_year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_profile', schema=None) as batch_op:
        batch_op.drop_column('founding_year')
        batch_op.drop_column('company_size')
        batch_op.drop_column('industry_category')

    # ### end Alembic commands ###
