"""feat: add master data tables

Revision ID: 23292b99521b
Revises: 8af1f7177a42
Create Date: 2026-07-09 11:02:00.325021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23292b99521b'
down_revision = '8af1f7177a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_code', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_location_code'), ['location_code'], unique=True)

    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_code', sa.String(length=50), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_skill_code'), ['skill_code'], unique=True)

    op.create_table('tech_stack_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tech_stack_code', sa.String(length=50), nullable=False),
    sa.Column('tech_stack_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tech_stack_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tech_stack_item_tech_stack_code'), ['tech_stack_code'], unique=True)

    op.create_table('technology_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_code', sa.String(length=50), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('technology_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_technology_category_category_code'), ['category_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technology_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_technology_category_category_code'))

    op.drop_table('technology_category')
    with op.batch_alter_table('tech_stack_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tech_stack_item_tech_stack_code'))

    op.drop_table('tech_stack_item')
    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_skill_code'))

    op.drop_table('skill')
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_location_code'))

    op.drop_table('location')
    # ### end Alembic commands ###
