"""Add internship_type and duration_months to Internship

Revision ID: 3eac27fb6698
Revises: 1976d3e4d596
Create Date: 2026-07-11 13:54:45.117398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eac27fb6698'
down_revision = '1976d3e4d596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('internship_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('duration_months', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internship', schema=None) as batch_op:
        batch_op.drop_column('duration_months')
        batch_op.drop_column('internship_type')

    # ### end Alembic commands ###
