"""add credential_url to certificate

Revision ID: 4834eb6d6355
Revises: a525df8aebe0
Create Date: 2026-07-10 14:16:45.149122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4834eb6d6355'
down_revision = 'a525df8aebe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_profile', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=150),
               existing_nullable=False)

    with op.batch_alter_table('student_certificate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credential_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('student_education_record', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('student_education_record_student_profile_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'student_profile', ['student_profile_id'], ['id'])

    with op.batch_alter_table('student_experience', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('student_experience_student_profile_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'student_profile', ['student_profile_id'], ['id'])

    with op.batch_alter_table('student_organization', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('student_organization_student_profile_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'student_profile', ['student_profile_id'], ['id'])

    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('student_profile_profile_photo_file_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'file_asset', ['profile_photo_file_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('student_skill', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('student_skill_student_profile_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'student_profile', ['student_profile_id'], ['id'])

    with op.batch_alter_table('student_tech_stack_item', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('student_tech_stack_item_student_profile_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'student_profile', ['student_profile_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_tech_stack_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('student_tech_stack_item_student_profile_id_fkey'), 'student_profile', ['student_profile_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('student_skill', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('student_skill_student_profile_id_fkey'), 'student_profile', ['student_profile_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('student_profile_profile_photo_file_id_fkey'), 'file_asset', ['profile_photo_file_id'], ['id'])

    with op.batch_alter_table('student_organization', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('student_organization_student_profile_id_fkey'), 'student_profile', ['student_profile_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('student_experience', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('student_experience_student_profile_id_fkey'), 'student_profile', ['student_profile_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('student_education_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('student_education_record_student_profile_id_fkey'), 'student_profile', ['student_profile_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('student_certificate', schema=None) as batch_op:
        batch_op.drop_column('credential_url')

    with op.batch_alter_table('company_profile', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
