"""add industry_category master & FK on company_profile

Revision ID: 5e2af557b2e3
Revises: 3eac27fb6698
Create Date: 2026-07-28 14:16:49.276689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e2af557b2e3'
down_revision = '3eac27fb6698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('industry_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_industry_category_code'), ['code'], unique=True)

    with op.batch_alter_table('application_interview', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_interview_internship_application_id'), ['internship_application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_interview_interview_status_id'), ['interview_status_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_interview_scheduled_at'), ['scheduled_at'], unique=False)

    with op.batch_alter_table('company_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('industry_category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'industry_category', ['industry_category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_profile', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('industry_category_id')

    with op.batch_alter_table('application_interview', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_interview_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_application_interview_interview_status_id'))
        batch_op.drop_index(batch_op.f('ix_application_interview_internship_application_id'))

    with op.batch_alter_table('industry_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_industry_category_code'))

    op.drop_table('industry_category')
    # ### end Alembic commands ###
