"""feat: add internship and application tables

Revision ID: 777c98348a28
Revises: ef4a6ade2409
Create Date: 2026-07-09 11:32:13.401655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '777c98348a28'
down_revision = 'ef4a6ade2409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_profile_id', sa.Integer(), nullable=False),
    sa.Column('technology_category_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('internship_title', sa.String(length=255), nullable=False),
    sa.Column('internship_description', sa.Text(), nullable=False),
    sa.Column('lifecycle_status_id', sa.Integer(), nullable=False),
    sa.Column('moderation_status_id', sa.Integer(), nullable=False),
    sa.Column('closing_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_profile_id'], ['company_profile.id'], ),
    sa.ForeignKeyConstraint(['lifecycle_status_id'], ['internship_lifecycle_status.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['moderation_status_id'], ['internship_moderation_status.id'], ),
    sa.ForeignKeyConstraint(['technology_category_id'], ['technology_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('internship_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('internship_id', sa.Integer(), nullable=False),
    sa.Column('application_status_id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('admin_decision_note', sa.Text(), nullable=True),
    sa.Column('submitted_cv_id', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_status_id'], ['application_status.id'], ),
    sa.ForeignKeyConstraint(['internship_id'], ['internship.id'], ),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profile.id'], ),
    sa.ForeignKeyConstraint(['submitted_cv_id'], ['file_asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('internship_moderation_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internship_id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('moderation_status_id', sa.Integer(), nullable=False),
    sa.Column('action_note', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['internship_id'], ['internship.id'], ),
    sa.ForeignKeyConstraint(['moderation_status_id'], ['internship_moderation_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('internship_required_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internship_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('required_level', sa.String(length=50), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['internship_id'], ['internship.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('internship_required_tech_stack_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internship_id', sa.Integer(), nullable=False),
    sa.Column('tech_stack_item_id', sa.Integer(), nullable=False),
    sa.Column('required_level', sa.String(length=50), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['internship_id'], ['internship.id'], ),
    sa.ForeignKeyConstraint(['tech_stack_item_id'], ['tech_stack_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_internship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('internship_id', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['internship_id'], ['internship.id'], ),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_interview',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internship_application_id', sa.Integer(), nullable=False),
    sa.Column('interview_status_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('meeting_link', sa.String(length=255), nullable=True),
    sa.Column('interview_notes', sa.Text(), nullable=True),
    sa.Column('interview_completed_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['internship_application_id'], ['internship_application.id'], ),
    sa.ForeignKeyConstraint(['interview_status_id'], ['interview_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_interview')
    op.drop_table('saved_internship')
    op.drop_table('internship_required_tech_stack_item')
    op.drop_table('internship_required_skill')
    op.drop_table('internship_moderation_event')
    op.drop_table('internship_application')
    op.drop_table('internship')
    # ### end Alembic commands ###
