"""feat: add lookup tables

Revision ID: 8af1f7177a42
Revises: 
Create Date: 2026-07-09 10:55:19.181836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8af1f7177a42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_skill_match_item_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_code', sa.String(length=50), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_skill_match_item_role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_skill_match_item_role_role_code'), ['role_code'], unique=True)

    op.create_table('application_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.String(length=50), nullable=False),
    sa.Column('status_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_status_status_code'), ['status_code'], unique=True)

    op.create_table('company_verification_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.String(length=50), nullable=False),
    sa.Column('status_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_verification_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_verification_status_status_code'), ['status_code'], unique=True)

    op.create_table('internship_lifecycle_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.String(length=50), nullable=False),
    sa.Column('status_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('internship_lifecycle_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_internship_lifecycle_status_status_code'), ['status_code'], unique=True)

    op.create_table('internship_moderation_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.String(length=50), nullable=False),
    sa.Column('status_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('internship_moderation_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_internship_moderation_status_status_code'), ['status_code'], unique=True)

    op.create_table('interview_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.String(length=50), nullable=False),
    sa.Column('status_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interview_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_status_status_code'), ['status_code'], unique=True)

    op.create_table('notification_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_code', sa.String(length=50), nullable=False),
    sa.Column('type_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_type_type_code'), ['type_code'], unique=True)

    op.create_table('report_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_code', sa.String(length=50), nullable=False),
    sa.Column('type_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_type_type_code'), ['type_code'], unique=True)

    op.create_table('user_account_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.String(length=50), nullable=False),
    sa.Column('status_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_account_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_account_status_status_code'), ['status_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_account_status_status_code'))

    op.drop_table('user_account_status')
    with op.batch_alter_table('report_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_type_type_code'))

    op.drop_table('report_type')
    with op.batch_alter_table('notification_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_type_type_code'))

    op.drop_table('notification_type')
    with op.batch_alter_table('interview_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_status_status_code'))

    op.drop_table('interview_status')
    with op.batch_alter_table('internship_moderation_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_internship_moderation_status_status_code'))

    op.drop_table('internship_moderation_status')
    with op.batch_alter_table('internship_lifecycle_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_internship_lifecycle_status_status_code'))

    op.drop_table('internship_lifecycle_status')
    with op.batch_alter_table('company_verification_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_verification_status_status_code'))

    op.drop_table('company_verification_status')
    with op.batch_alter_table('application_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_status_status_code'))

    op.drop_table('application_status')
    with op.batch_alter_table('ai_skill_match_item_role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_skill_match_item_role_role_code'))

    op.drop_table('ai_skill_match_item_role')
    # ### end Alembic commands ###
