"""feat: add ai feature tables

Revision ID: 8f68334d7de4
Revises: 777c98348a28
Create Date: 2026-07-09 11:36:10.607011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f68334d7de4'
down_revision = '777c98348a28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_job_recommendation_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('input_snapshot_hash', sa.String(length=255), nullable=True),
    sa.Column('input_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('generation_status', sa.String(length=50), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_job_recommendation_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_job_recommendation_run_id', sa.Integer(), nullable=False),
    sa.Column('internship_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('recommendation_reason', sa.Text(), nullable=True),
    sa.Column('rank_no', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ai_job_recommendation_run_id'], ['ai_job_recommendation_run.id'], ),
    sa.ForeignKeyConstraint(['internship_id'], ['internship.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_skill_match_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('internship_id', sa.Integer(), nullable=False),
    sa.Column('match_percentage', sa.Float(), nullable=True),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('suggested_skills_summary', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('input_snapshot_hash', sa.String(length=255), nullable=True),
    sa.Column('input_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('generation_status', sa.String(length=50), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['internship_id'], ['internship.id'], ),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_skill_match_skill_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_skill_match_run_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('item_role_id', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ai_skill_match_run_id'], ['ai_skill_match_run.id'], ),
    sa.ForeignKeyConstraint(['item_role_id'], ['ai_skill_match_item_role.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_skill_match_tech_stack_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_skill_match_run_id', sa.Integer(), nullable=False),
    sa.Column('tech_stack_item_id', sa.Integer(), nullable=False),
    sa.Column('item_role_id', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ai_skill_match_run_id'], ['ai_skill_match_run.id'], ),
    sa.ForeignKeyConstraint(['item_role_id'], ['ai_skill_match_item_role.id'], ),
    sa.ForeignKeyConstraint(['tech_stack_item_id'], ['tech_stack_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_skill_match_tech_stack_item')
    op.drop_table('ai_skill_match_skill_item')
    op.drop_table('ai_skill_match_run')
    op.drop_table('ai_job_recommendation_item')
    op.drop_table('ai_job_recommendation_run')
    # ### end Alembic commands ###
