"""feat: add notification and admin tables

Revision ID: d5fa4a71a08d
Revises: 8f68334d7de4
Create Date: 2026-07-09 11:43:03.501655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5fa4a71a08d'
down_revision = '8f68334d7de4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('action_code', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type_id', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('event_at', sa.DateTime(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notification_type_id'], ['notification_type.id'], ),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_type_id', sa.Integer(), nullable=False),
    sa.Column('generated_by_user_id', sa.Integer(), nullable=False),
    sa.Column('filters_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('report_file_asset_id', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['report_file_asset_id'], ['file_asset.id'], ),
    sa.ForeignKeyConstraint(['report_type_id'], ['report_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_report')
    op.drop_table('notification')
    op.drop_table('admin_audit_log')
    # ### end Alembic commands ###
