"""feat: add company domain tables

Revision ID: ef4a6ade2409
Revises: d3894ecb9e13
Create Date: 2026-07-09 11:24:34.552796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef4a6ade2409'
down_revision = 'd3894ecb9e13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_social_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_profile_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_profile_id'], ['company_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_verification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_profile_id', sa.Integer(), nullable=False),
    sa.Column('verification_status_id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['company_profile_id'], ['company_profile.id'], ),
    sa.ForeignKeyConstraint(['verification_status_id'], ['company_verification_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_verification')
    op.drop_table('company_social_link')
    # ### end Alembic commands ###
